In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a+1

array([2, 3, 4, 5])

In [5]:
a = np.ones(4)

In [6]:
a

array([1., 1., 1., 1.])

In [7]:
b = a+1

In [8]:
b

array([2., 2., 2., 2.])

In [9]:
a-b

array([-1., -1., -1., -1.])

In [10]:
a * b

array([2., 2., 2., 2.])

In [11]:
c = np.diag([1,2,3,4])

In [12]:
c * c

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [13]:
#Another way

In [14]:
c.dot(c)

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [15]:
a

array([1., 1., 1., 1.])

In [16]:
b

array([2., 2., 2., 2.])

In [17]:
a = np.array([1,2,3,4])

In [18]:
b = np.array([5,2,2,4])

In [19]:
a == b

array([False,  True, False,  True])

In [20]:
#Element wise comparison

In [21]:
a > b

array([False, False,  True, False])

In [22]:
a = np.array([0,0,1,1],dtype = bool)

In [23]:
b = np.array([0,1,1,1],dtype = bool)

In [24]:
np.logical_and(a,b)

array([False, False,  True,  True])

In [25]:
a = np.arange(5)

In [26]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [27]:
np.log(a)

/home/karthikeyan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [28]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [29]:
#If shape mismatch , can't do mathematical operations with numpy arrays

In [30]:
a = np.arange(4)

In [31]:
a + np.array([4,5])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

**Basic reductions**

In [32]:
a = np.array([1,2,3,4])
np.sum(a)

10

In [33]:
a = np.array([[1,1],[2,2]])

In [34]:
a

array([[1, 1],
       [2, 2]])

In [35]:
a.sum(axis =0) #Columns first dimension

array([3, 3])

In [36]:
a.sum(axis = 1) #Row wise sums

array([2, 4])

In [37]:
a = np.array([1,2,3,4])

In [38]:
a.min()

1

In [39]:
a.max()

4

In [40]:
np.all([True,True,True]) #All true returns true

True

In [41]:
np.all([True,False,True]) #If one false return false

False

In [42]:
np.any([True,False,True]) #Any one is true returns True

True

In [43]:
np.any([False,False,False]) #If all false returns false

False

In [44]:
np.all( a == a)

True

In [45]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

In [46]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

In [47]:
x.mean()

1.75

In [48]:
np.median(x)

1.5

In [49]:
np.mean(x)

1.75

In [50]:
np.median(y, axis = 1) #Last axis

array([2., 5.])

In [51]:
np.std(x)

0.82915619758885

**Load from Txt file in NP**

In [52]:
data = np.loadtxt('populations.txt')

In [53]:
pwd

'/home/karthikeyan/Documents/Applied AI Course/Numpy'

In [54]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [55]:
years , hares , lynxes, carrots = data.T #Transposefn , done to make columns as variables

In [56]:
years

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [57]:
populations = data[:,1:]

In [58]:
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [59]:
populations.std(axis = 0)
#Sample standard deviations

array([20897.90645809, 16254.59153691,  3322.50622558])

In [60]:
np.argmax(populations,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

**Broadcasting**

In [61]:
a = np.tile(np.arange(0,40,10),(3,1))

In [62]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [63]:
a = np.tile(np.arange(0,40,10),(3,2))
a

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [64]:
a = a.T

In [65]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [66]:
a = np.array([[1,2,3],[4,5,6]])

In [67]:
a.ravel() #returns a flatened contigous 1D array

array([1, 2, 3, 4, 5, 6])

In [68]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
a.shape

(2, 3)

In [70]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
b = a.ravel()

In [72]:
b

array([1, 2, 3, 4, 5, 6])

In [73]:
b=b.reshape((2,3))

In [74]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
b[0,0] = 100

In [76]:
b

array([[100,   2,   3],
       [  4,   5,   6]])

In [77]:
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [78]:
#a also changes

In [79]:
#reshape also may return a copy

In [80]:
a = np.zeros((3, 2))
b = a.T.reshape(3*2)
b[0] = 50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [81]:
a = np.array([1,2,3])

In [82]:
a

array([1, 2, 3])

In [83]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [84]:
a = np.arange(4*3*2).reshape(4,3,2)

In [85]:
a.shape

(4, 3, 2)

In [86]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [87]:
a[0,2,1]

5

In [88]:
a = np.arange(4)

In [89]:
a.resize(8)

In [90]:
a.resize((8))

In [91]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [92]:
b = a

In [93]:
a.resize((4))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [94]:
#Sorting
a = np.array([[5,4,6],[2,3,2]])

In [95]:
a

array([[5, 4, 6],
       [2, 3, 2]])

In [96]:
b = np.sort(a,axis=1)

In [97]:
b

array([[4, 5, 6],
       [2, 2, 3]])

In [98]:
a.sort(axis=1)

In [99]:
a

array([[4, 5, 6],
       [2, 2, 3]])

In [100]:
#Fancy indexing

In [101]:
a = np.array([4,3,1,2])

In [102]:
j = np.argsort(a)

In [103]:
j

array([2, 3, 1, 0])

In [104]:
a[j]

array([1, 2, 3, 4])