In [1]:
'''
Powerful Numerical processing library
It give python an extension for multi dimensional array
super efficient and convenience
array oriented computing
'''

'\nPowerful Numerical processing library\nIt give python an extension for multi dimensional array\nsuper efficient and convenience\narray oriented computing\n'

In [2]:
import numpy as np
a = np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
%timeit [i*2 for i in range(1,5)]

705 ns ± 10.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [4]:
%timeit np.arange(1,5) *2

4.16 µs ± 57.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
'''
Cpmpare the both above LOC, u can see numpy array executes faster
'''

'\nCpmpare the both above LOC, u can see numpy array executes faster\n'

In [6]:
#Creating arrays

In [7]:
a = np.array([1,2,3])

In [8]:
a

array([1, 2, 3])

In [9]:
a.ndim

1

In [10]:
a.shape

(3,)

In [11]:
len(a)

3

In [12]:
b = np.array([[0,1,2],[3,4,5]])

In [13]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 3)

In [16]:
len(b)

2

In [17]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

In [18]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
#we HAVE LIST WITHIN LIST WITHIN LIST

In [20]:
c.ndim

3

In [21]:
c.shape

(2, 2, 2)

In [22]:
 '''
 1D array -> Vectors
 2D array -> Matrix
 ND array -> Tensor
 
 '''

'\n1D array -> Vectors\n2D array -> Matrix\nND array -> Tensor\n\n'

In [23]:
b = np.arange(1,10,2)
#start , end , step size

In [24]:
b

array([1, 3, 5, 7, 9])

In [25]:
b = np.linspace(0,1,6)
#start, end No of points

In [26]:
b

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [27]:
a = np.ones((3,3))#Tuple passed in fn

In [28]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#Gives a 3*3 identity matrix

In [32]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [33]:
a = np.diag([1,2,3,4]) #Constructs a diagonal array

In [34]:
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [35]:
np.diag(a)

array([1, 2, 3, 4])

In [36]:
a = np.random.rand(4)

In [37]:
a

array([0.19900345, 0.59024071, 0.07856557, 0.21223941])

In [38]:
#random -> package
#rand is a fn

In [39]:
a = np.random.randn(4)
#randn -> random normal fn

In [40]:
a

array([-1.55388624,  0.1672902 ,  0.61831138,  1.56500687])

In [41]:
# diff between rand and randn -> refer to probability and statistics

In [42]:
a = np.arange(10)

In [43]:
a.dtype

dtype('int64')

In [44]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a = np.arange(10,dtype='float64')

In [46]:
a.dtype

dtype('float64')

In [47]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
np.zeros(3)
#Whenever we use np.zeros or ones the default data type is float Not int

array([0., 0., 0.])

In [49]:
d = np.array([1+2j,3+4j])

In [50]:
d

array([1.+2.j, 3.+4.j])

In [51]:
d.dtype

dtype('complex128')

In [52]:
d = np.array([True,False])

In [53]:
d.dtype

dtype('bool')

In [54]:
d = np.array(['dsubhja','feiahfb','doijvno'])

In [55]:
d.dtype

dtype('<U7')

In [56]:
# U means 'U'	Unicode string

In [57]:
a = np.arange(10)#Indices begin at zero

In [58]:
a[5]

5

In [59]:
a = np.diag([1,2,3])

In [60]:
a[2,2]
#Gives second row and second col element

3

In [61]:
a = np.arange(10)

In [62]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a[1:8:2]
#Start , end, step

array([1, 3, 5, 7])

In [64]:
a[5:] = 10
#Change from 5th element to last elemet to 10

In [65]:
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [66]:
b = np.arange(5)

In [67]:
a[5:] = b[::-1]#assigning

In [68]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [69]:
a = np.arange(10)

In [70]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
b = a[::2]

In [72]:
b

array([0, 2, 4, 6, 8])

In [73]:
np.shares_memory(a,b)

True

In [74]:
'''
Bt using view method , The elements in b shares memory with elements in a ,
coz it's memory efficient
'''

"\nBt using view method , The elements in b shares memory with elements in a ,\ncoz it's memory efficient\n"

In [75]:
#Some defects are as follows

In [76]:
b[0] = 10

In [77]:
b

array([10,  2,  4,  6,  8])

In [78]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [79]:
#If u change b it also affects a

In [80]:
#to overcome this we use force copy

In [81]:
a = np.arange(10)

In [82]:
c = a[::2].copy()

In [83]:
c

array([0, 2, 4, 6, 8])

In [84]:
np.shares_memory(a,c)

False

In [85]:
c[0] = 10

In [86]:
c

array([10,  2,  4,  6,  8])

In [87]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Fancy Indexing**

In [88]:
a = np.random.randint(0,20,15)

In [89]:
a

array([ 4,  1,  4, 10, 18,  2, 14, 19, 11, 17, 14,  1,  2, 19,  6])

In [90]:
mask = (a % 2 ==0)

In [91]:
from_a = a[mask]

In [92]:
from_a

array([ 4,  4, 10, 18,  2, 14, 14,  2,  6])

In [93]:
'''
Masks create copies , not views
'''

'\nMasks create copies , not views\n'

In [94]:
a[mask] = -1

In [95]:
a

array([-1,  1, -1, -1, -1, -1, -1, 19, 11, 17, -1,  1, -1, 19, -1])

In [96]:
# This has converted all even no to -1

In [97]:
a[[2,3,2,4,2]]

array([-1, -1, -1, -1, -1])

In [98]:
a[[9,7]] = 200

In [99]:
a

array([ -1,   1,  -1,  -1,  -1,  -1,  -1, 200,  11, 200,  -1,   1,  -1,
        19,  -1])

In [100]:
a.dtype

dtype('int64')